name: Ruby CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted, linux, arm64, docker]
    
    strategy:
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', '3.3']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Run tests
      run: bundle exec rspec
      
    - name: Run RuboCop
      run: bundle exec rubocop || true
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-ruby-${{ matrix.ruby-version }}
        path: coverage/
        
  build:
    runs-on: [self-hosted, linux, arm64, docker]
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Build gem
      run: gem build *.gemspec
      
    - name: Upload gem artifact
      uses: actions/upload-artifact@v4
      with:
        name: ruby-gem
        path: '*.gem'
        
  code-quality:
    runs-on: [self-hosted, linux, arm64, docker]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby 3.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Run RuboCop
      run: bundle exec rubocop || true
      
    - name: Generate documentation
      run: bundle exec yard doc || true
